-- Run this once in Supabase Dashboard > SQL Editor for your project.

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    student_name text not null check (char_length(btrim(student_name)) between 1 and 100),
    usn text not null unique check (char_length(usn) between 1 and 40 and usn = upper(btrim(usn))),
    course text not null check (course in ('BCA', 'BCom', 'BCom Evening', 'BSALP', 'PUC')),
    study_year text not null,
    gender text not null check (gender in ('Male', 'Female')),
    created_at timestamptz not null default now(),
    constraint students_year_matches_course check (
        (course = 'PUC' and study_year in ('PUC 1st Year', 'PUC 2nd Year'))
        or
        (course <> 'PUC' and study_year in ('1st Year', '2nd Year', '3rd Year'))
    )
);

create table if not exists public.student_events (
    student_id bigint not null references public.students(id) on delete cascade,
    event_name text not null check (event_name in (
        '100m', '200m', '400m', '800m',
        'Long Jump', 'High Jump', 'Discus Throw', 'Shot Put'
    )),
    primary key (student_id, event_name)
);

create index if not exists student_events_event_name_idx
    on public.student_events (event_name);

create table if not exists public.sports_day_admins (
    user_id uuid primary key references auth.users(id) on delete cascade,
    created_at timestamptz not null default now()
);

alter table public.students enable row level security;
alter table public.student_events enable row level security;
alter table public.sports_day_admins enable row level security;

revoke all on table public.students, public.student_events, public.sports_day_admins
    from public, anon, authenticated;
grant usage on schema public to anon, authenticated;
grant select on table public.students, public.student_events, public.sports_day_admins
    to authenticated;

create or replace function public.is_sports_day_admin()
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
    select exists (
        select 1
        from public.sports_day_admins
        where user_id = (select auth.uid())
    );
$$;

drop policy if exists "admins can read students" on public.students;
create policy "admins can read students"
    on public.students for select to authenticated
    using ((select public.is_sports_day_admin()));

drop policy if exists "admins can read student events" on public.student_events;
create policy "admins can read student events"
    on public.student_events for select to authenticated
    using ((select public.is_sports_day_admin()));

drop policy if exists "admins can read own membership" on public.sports_day_admins;
create policy "admins can read own membership"
    on public.sports_day_admins for select to authenticated
    using (user_id = (select auth.uid()));

revoke execute on function public.is_sports_day_admin() from public, anon, authenticated;
grant execute on function public.is_sports_day_admin() to authenticated;

-- Remove the starter function signature before installing the version that
-- accepts the current frontend registration form. Also remove the expanded
-- version from an earlier build if it has already been installed.
drop function if exists public.register_student(text, text, text, text, text, text[]);
drop function if exists public.register_student(text, text, text, text, text, text, text, text, text[]);

create or replace function public.register_student(
    p_name text,
    p_usn text,
    p_course text,
    p_year text,
    p_gender text,
    p_events text[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_usn text;
    v_student_id bigint;
    v_track_count integer;
    v_field_count integer;
begin
    if p_name is null or char_length(btrim(p_name)) not between 1 and 100 then
        raise exception using errcode = '22023', message = 'Enter a name up to 100 characters long.';
    end if;

    if p_usn is null or char_length(btrim(p_usn)) not between 1 and 40 then
        raise exception using errcode = '22023', message = 'Enter a student ID up to 40 characters long.';
    end if;

    if p_course is null or p_course not in ('BCA', 'BCom', 'BCom Evening', 'BSALP', 'PUC') then
        raise exception using errcode = '22023', message = 'Select a valid course.';
    end if;

    if p_year is null
       or (p_course = 'PUC' and p_year not in ('PUC 1st Year', 'PUC 2nd Year'))
       or (p_course <> 'PUC' and p_year not in ('1st Year', '2nd Year', '3rd Year')) then
        raise exception using errcode = '22023', message = 'Select a valid year for the chosen course.';
    end if;

    if p_gender is null or p_gender not in ('Male', 'Female') then
        raise exception using errcode = '22023', message = 'Select a valid gender.';
    end if;

    if p_events is null or cardinality(p_events) not between 1 and 3
       or array_position(p_events, null) is not null then
        raise exception using errcode = '22023', message = 'Select between 1 and 3 events.';
    end if;

    if cardinality(p_events) <> (
        select count(distinct selected.event_name)::integer
        from unnest(p_events) as selected(event_name)
    ) then
        raise exception using errcode = '22023', message = 'An event was selected more than once.';
    end if;

    if exists (
        select 1 from unnest(p_events) as selected(event_name)
        where selected.event_name not in (
            '100m', '200m', '400m', '800m',
            'Long Jump', 'High Jump', 'Discus Throw', 'Shot Put'
        )
    ) then
        raise exception using errcode = '22023', message = 'One or more selected events are invalid.';
    end if;

    select
        count(*) filter (where selected.event_name in ('100m', '200m', '400m', '800m')),
        count(*) filter (where selected.event_name in ('Long Jump', 'High Jump', 'Discus Throw', 'Shot Put'))
    into v_track_count, v_field_count
    from unnest(p_events) as selected(event_name);

    if v_track_count > 2 or v_field_count > 2 then
        raise exception using errcode = '22023', message = 'Choose no more than 2 track events and 2 field events.';
    end if;

    if p_gender = 'Female' and '800m' = any(p_events) then
        raise exception using errcode = '22023', message = '800 Metre is available for male students only.';
    end if;

    v_usn := upper(btrim(p_usn));

    insert into public.students (student_name, usn, course, study_year, gender)
    values (btrim(p_name), v_usn, p_course, p_year, p_gender)
    returning id into v_student_id;

    insert into public.student_events (student_id, event_name)
    select v_student_id, selected.event_name
    from unnest(p_events) as selected(event_name);

    return jsonb_build_object(
        'registrationId', v_student_id,
        'events', to_jsonb(p_events)
    );
end;
$$;

revoke execute on function public.register_student(text, text, text, text, text, text[])
    from public, anon, authenticated;
grant execute on function public.register_student(text, text, text, text, text, text[])
    to anon, authenticated;
